### ISSUE TITLE
V2 Animation Framework

### ISSUE THREAD

**Issue by bogobogo** [wix/react-native-navigation#2435]
Create an animation framework that allows the user to define animations in the js side.
Current proposed API:

## API

```js
Navigation.push(this.props.componentId, {
  name: 'navigation.playground.CustomTransitionDestination',
  options: {
    animations: {
      push: {
        topBar: {
          id: 'STACK_ID' // Id of the stack containing the TopBar to animate
        },
        bottomTabs: {
          id: 'BOTTOM_TABS_ID'
        },
        content: {
          y: {
            from: 0,
            to: 200,
            duration: 150,
            interpolation: 'decelerate',
            startDelay: 100
          },
          alpha: {
            from: 0,
            to: 1,
            duration: 150
          }
        }
      },
      pop: {},
      showModal: {},
      dismissModal: {}
    }
  }
})
```

## Android
- [x] navigationOptions should be accessible through a ViewController #2440 
- [x] merge animations into navigationOptions
- [x] y
- [x] x
- [x] alpha
- [x] duration
- [x] interpolation
- [x] startDelay
- [x] Animate topBar and bottomTabs

* Support custom animations for the following commands:
- [x] push #2436 
- [x] pop #2437 
- [x] startApp #2438 
- [x] show/hide Modal #2790

* Support for default app animation style in `setDefaultOptions`

## iOS
- [x] navigationOptions should be accessible through a ViewController #2440 
- [x] merge animations into navigationOptions
- [x] y
- [x] x
- [x] alpha
- [x] duration
- [x] interpolation
- [x] startDelay
- [x] Animate topBar and bottomTabs

* Support custom animations for the following commands:
- [x] push
- [x] pop
- [x] ~~startApp~~ https://github.com/wix/react-native-navigation/issues/2901
- [x] showModal
- [x] dismissModal

* Support for default app animation style in `setDefaultOptions`

**Comment by brunolemos** [comment]
iOS too I suppose?

**Comment by kyle-ssg** [comment]
Quick question about this, I see that you can define push / pop / openModal etc animations from pushing to a page, this makes sense (especially defining a pop animation for a push).

More often than not though I could see the need to define the animation for just the screen I am transitioning to case e.g.

```Navigation.openModal(this.props.componentId, {
  name: 'navigation.playground.MyFadeModal',
..animationProps
})
```


Will this be possible too ?

**Comment by guyca** [comment]
Yes. You'll be able to define keep the default animations provided by RNN, declare default animations once for each command (using `Navigation.setDefaultOptions` api) and you'll also be able to override animations whenever you)

**Comment by rpmonteiro** [comment]
Is this working already? Is the API exactly as you described it above?

**Comment by guyca** [comment]
@rpmonteiro This feature is already available. You can find examples in the [playground app](https://github.com/wix/react-native-navigation/blob/v2/playground/src/app.js#L27) (obviously remove the underscore from `_animations`)

**Comment by yusufyildirim** [comment]
I think we need for setRoot too

**Comment by chrisbenincasa** [comment]
+1 for having animations for setRoot

**Comment by guyca** [comment]
@chrisbenincasa @yusufyildirim You can customise `setRoot` animation in `startApp` animation. This will corrected soon to `setRoot` as expected. Sorry for the confusion.

**Comment by ebouJ** [comment]
@guyca is there a way to slide the screen from left to right instead of bottom to up in android? v2

**Comment by guyca** [comment]
@ebouJ 
Sure, Animate the `x` value of `content`. I haven't tried it myself but it should work 👍 
I'd like to create an animation section in the documentation, would be nice if you contributed your slide animation to that 👍 🙏

**Comment by chrisbenincasa** [comment]
Will iOS support the `startApp`/`setRoot` animation?

**Comment by GuillotJessica** [comment]
```
Navigation.setDefaultOptions({
    bottomTabs: {
animated: false or true
}
```
changed nothing, there always some kind of animation on going...

also, I've been integrating v2 for a week and v1 a few day ahead and at some point I've got a very nice animation that when tab was not selected, there was only the icon and once selected the icon has size changed and text displayed, I wonder if it has something to do with animationType i can't see no more in v2, or any other exemple i saw but can't put my finger on anymore, any clue will be very much appreciated

**Comment by chrisehlee** [comment]
@ebouJ Where you able to accommplish what you wanted (and if so please do you mind sharing your code 😉)

**Comment by Lube** [comment]
@Annihil could you provide a sample code? I cannot get it to work!

**Comment by iksent** [comment]
"react-native-navigation": "^2.0.2459"
"react": "16.3.1",
"react-native": "0.55.4",

   ```    animations: {
            startApp: { // Not working
                y: {
                    from: 1000,
                    to: 0,
                    duration: 2500,
                },
                alpha: {
                    from: 0,
                    to: 1,
                    duration: 2400,
                }
            },
            push: { // It works! Push with animation from right to left
                content: {
                    x: {
                        from: 1000,
                        to: 0,
                        duration: 300,
                    },
                    alpha: {
                        from: 0.5,
                        to: 1,
                        duration: 300,
                    }
                }
            },
            pop: { // Not working
                content: {
                    x: {
                        from: 0,
                        to: 1000,
                        duration: 2300,
                    },
                    alpha: {
                        from: 1,
                        to: 0.5,
                        duration: 2300,
                    }
                }
            },
        }
```

**Comment by guyca** [comment]
As the animation feature is already implemented, there's no need for further discussion in this issue. If anyone encounters bugs or issues, please open a new issue.
