### ISSUE TITLE
Migrate Espresso tests suite to Detox

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2792]
### Application Lifecycle tests
- [x] relaunchFromBackground
- [x] relaunchAfterClose
- [x] deviceOrientationDoesNotDestroyActivity
- [x] relaunchAfterActivityKilledBySystem 
  >Requires fix in Detox
  >```js
  >this.instrumentationProcess.on('close', (code, signal) => {
  >  log.verbose(`instrumentationProcess terminated due to receipt of signal ${signal}`);
  >  this.terminateInstrumentation(); // <<
  >});
  >```
- [ ] pressingMenuOpensDevMenu 🛑 Detox fails to interact with Dialog https://github.com/wix/detox/issues/607
- [ ] pressingRTwiceInSuccessionReloadsReactNative 🛑https://github.com/wix/detox/issues/608
>Detox times out with `onMessage: {"messageId":3,"type":"error","params":{"error":"Wait for [com.wix.detox.espresso.ReactNativeUIModuleIdlingResource] to become idle timed out"}}`
- [x] pressingRTwiceWithDelayDoesNothing
- [ ] sendingReloadBroadcastReloadsReactNative 🛑 Detox hangs https://github.com/wix/detox/issues/608

### BackHandlerTest
- [x] overrideHardwareBackButton

### Modal
- [x] pushIntoModal
- [x] backPopsModalStack

### OverlayTest
> Implemented in `ScreenStack.js`
- [x] testOverlayAlertAppear
- [x] testOverlayNotInterceptingTouchEvents

### StaticLifecycleEvents
- [x] didAppearDidDisappear

### top level api
- [ ] switch to tabs with side menus 🛑 https://github.com/wix/detox/issues/566

### orientation
Skipped all orientation tests for now as they are flaky in RN 0.51
- [ ] portrait only 🛑 https://github.com/wix/detox/issues/599
- [ ] landscape only 🛑 https://github.com/wix/detox/issues/599

### screen style
- [x] stack options should not override component options

**Comment by DanielZlotin** [comment]
Removed old suite, updated docs and scripts

**Comment by DanielZlotin** [comment]
Not closing as there are still TODOs
maybe open other issue on those?

**Comment by Rob117** [comment]
@DanielZlotin  This is the issue where we should track android support for RN > 50(51?), right?

**Comment by DanielZlotin** [comment]
All e2e are with detox

**Comment by guyca** [comment]
We're waiting for a few unimplemented features in Detox to finish the migration, most notably UiAutomator support.

**Comment by jalooc** [comment]
Any success with opening side menu in Detox? (https://github.com/wix/Detox/issues/566)
