### ISSUE TITLE
Shared Element Transition Android

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3602]
# Phase 1
- [x] Parse `customTransition` options
- [x] Register elements in parent ReactView
- [x] Pass from and to elements to `ElementTransitionManager`
- [x] Calculate animators
  - [x] x, y
  - [x] image matrix
- [x] Handle Z index (❕Use `zIndex` prop)

# Phase 2
- [x] Calculate animators
  - [x] ScaleX, ScaleY
  - [x] View background color
  - [x] Text size
  - [x] Text color (❕`color` has to be declared in both from and to `Text` elements)
- [x] Fork [Reflow Animator](https://github.com/shazam/reflow-animator/) as a few changes are needed to support animating `ReactTextView`

# Phase 3
- [ ] Hide from elements when animation starts
- [ ] Support transitions in all commands
  - [ ] pop
  - [ ] showModal
  - [ ] dismissModal
- [ ] Support animating elements in complex layouts. For example when pushing a `TopTabs` layout who's first child contains shared elements
- [ ] Use Cross fade animation by default instead of the default push/showModal animations.<br>Currently I'm working around this by setting a fade animations in options, for example during [pop](https://github.com/wix/react-native-navigation/blob/sharedElementTransitionAndroid/playground/src/screens/CustomTransitionDestination.js#L28)
- [ ] Regular Transitions with no shared views, meaning end or start properties (depending on push/pop show/hide modal) are defined in js
- [ ] Always wait for render when Shared Element Transition is used 
- [ ] interpolation
- [ ] Support regular transitions (non shared element transitions)

**Comment by laurentrivard** [comment]
hey @guyca thanks for working on this! Do you have an ETA on when SharedElementTransition will be functional on Android? 

I appreciate you guys!!

**Comment by guyca** [comment]
Hey @laurentrivard, unfortunately no eta as we're not actively working on this. If someone would like to finish the work already started then please ping me either here or on discord.

**Comment by pie6k** [comment]
I think it should not be marked as 'done'

![image](https://user-images.githubusercontent.com/7311462/56020327-3103d600-5d07-11e9-9b93-35a00e0e17a7.png)

**Comment by FinnGu** [comment]
This feature is not implemented yet, right? I am just wondering, because the documentation makes it look like a working feature.
Or is it implemented in iOS, but not in Android?

**Comment by GioLogist** [comment]
@FinnGu Currently experimenting with it on iOS and it's working great for the most part! Easy to use API and feels just as native as the navigation.

**Comment by FinnGu** [comment]
Apparently RNN v5.0.0 includes a completely new implementation of Shared Element Transitions. Right now push and pop is possible on iOS and push is working on Android. Pop animations on Android are supposed to come very soon.

Just in case, some of you have not seen the update :)

**Comment by guyca** [comment]
Closing this issue as it relates to the previous implementation. Will open a new issue to track progress on missing features 👍
