### ISSUE TITLE
[Epic] React Native 73 Support

### ISSUE THREAD

**Issue by d4vidi** [wix/react-native-navigation#7834]
```[tasklist]
### Tasks
- [ ] https://github.com/wix/react-native-navigation/issues/7835
- [ ] https://github.com/wix/react-native-navigation/issues/7836
- [ ] https://github.com/wix/react-native-navigation/issues/7837
- [ ] https://github.com/wix/react-native-navigation/issues/7838
```

Also related:
- [x] https://github.com/wix/react-native-navigation/issues/7825
- [x] https://github.com/wix/react-native-navigation/issues/7821
- [x] https://github.com/wix/react-native-navigation/issues/7852

**Comment by bogoslavskiy** [comment]
How long wait ?

**Comment by EDFrontend** [comment]
Guys, in my case, your library is the only one that doesn't allow migration. It's been a while already.

**Comment by yevhenlv** [comment]
Guys, in my case, your library is the only one that doesn't allow migration. It's been a while already.

**Comment by vincentzierigen** [comment]
I need this migration, why is it taking so long?

**Comment by gosha212** [comment]
@yevhenlv please use 7.38.6 version. It is RC. A final version will be released very soon (days)

**Comment by retyui** [comment]
@d4vidi Review pls https://github.com/wix/react-native-navigation/pull/7944
