### ISSUE TITLE
[Epic] React Native 74 Support

### ISSUE THREAD

**Issue by d4vidi** [wix/react-native-navigation#7910]
```[tasklist]
### Tasks
- [ ] [RN74] Support for Android
- [ ] [RN74] Support for iOS
- [ ] [RN74] Docs alignment
- [ ] [RN74] Wix-internal rollout
```

Related issues/PR's to revisit:
- https://github.com/wix/react-native-navigation/pull/7886
- https://github.com/wix/react-native-navigation/issues/7874
-
