### ISSUE TITLE
[Epic] Navigation 🧭 KTLO 

### ISSUE THREAD

**Issue by d4vidi** [wix/react-native-navigation#7938]
```[tasklist]
### Tasks
- [ ] https://github.com/wix/react-native-navigation/issues/7939
- [ ] https://github.com/wix/react-native-navigation/issues/7937
- [ ] https://github.com/wix/react-native-navigation/issues/7940
- [ ] https://github.com/wix/react-native-navigation/issues/7941
- [ ] https://github.com/wix/react-native-navigation/issues/7971
- [ ] https://github.com/wix/react-native-navigation/issues/7966
- [ ] https://github.com/wix/react-native-navigation/issues/7972
- [ ] https://github.com/wix/react-native-navigation/issues/7968
```
